version: '3'
services:
  documents:
    image: documents_service
    build: ./document_service
    ports:
      - "8083:8083"
    command: ["./DocumentServiceServer","-host","http://documents:8083"]
    depends_on:
      - data_seed
#      data_seed:
#        condition: service_healthy
      - database
#          condition: service_healthy

  database:
    image: db_service
    build: ./db_service
    ports:
      - "8082:8082"
    command: ["./DbServiceServer","-bind","http://database:8082","-db","coke"]
    healthcheck:
      test: ["CMD-SHELL", "curl  http://database:8082/HealthCheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_seed:
    image: data_seeder
    build: ./data_seed_service
    command: ["./DataSeeder","-dbHost","http://database:8082"]
    depends_on:
      - database

  health_check:
    image: health_check_service
    build: ./health_checker_service
    command: ["./HealthChecker","-dbHost","http://database:8082"]

