version: '3'
services:
  documents:
    image: documents_service
    build: ./document_service
    ports:
      - "8083:8083"
    command: ["./DocumentServiceServer","-host","http://documents:8083"]
    depends_on:
      - data_seed

  database:
    image: db_service
    build: ./db_service
    ports:
      - "8082:8082"
    command: ["./DbServiceServer","-host","http://database:8082"]

  data_seed:
    image: data_seeder
    build: ./data_seed_service
    command: ["./DataSeeder","-dbHost","http://database:8082"]
    depends_on:
      - database


  health_check:
    image: health_check_service
    build: ./health_checker_service
    command: ["./HealthChecker"]

